"""Make user_id nullable

Revision ID: 213fa5d49227
Revises: 68856aa61eab
Create Date: 2025-10-01 20:13:42.317346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213fa5d49227'
down_revision = '68856aa61eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('minutes_to_complete',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('minutes_to_complete',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
